name: 'Rebase Branch'
description: 'Attempts to rebase the current branch of a Git repository.'
author: 'Martin Costello'
branding:
  icon: 'git-branch'
  color: 'green'
inputs:
  branch:
    description: 'The optional branch to rebase the current branch onto.'
    required: false
    default: ''
  repository:
    description: 'The optional path of the repository to rebase.'
    required: false
    default: ''
  user-email:
    description: 'The optional email address to use for Git commit(s).'
    required: false
    default: 'github-actions[bot]@users.noreply.github.com'
  user-name:
    description: 'The optional user name to use for Git commit(s).'
    required: false
    default: 'github-actions[bot]'
outputs:
  result:
    description: 'The result of attempting to rebase the branch. The value is one of: upToDate, success, conflicts or error.'
runs:
  using: 'node16'
  main: 'dist/index.js'
